### ISSUE TITLE
抽奖号码重复

### ISSUE THREAD

**Issue by Vondser** [vitozyf/lucky-draw#10]
一等奖和五等奖抽完后，删除一等奖的号码再重抽一等奖，抽出来的号码会和五等奖里面的重复

**Comment by vitozyf** [comment]
> 一等奖和五等奖抽完后，删除一等奖的号码再重抽一等奖，抽出来的号码会和五等奖里面的重复

确认抽奖时是否开启了全员参与功能。未测试出这个问题。
