### ISSUE TITLE
有没有本地下载使用的文件？

### ISSUE THREAD

**Issue by s1mple-zzy** [vitozyf/lucky-draw#12]

**Comment by vitozyf** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    现在有windows软件版本，你可以直接下载使用
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhangyongfeng5350
                            
                    
                        
                            
                                    zhangyongfeng5350@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年01月7日 22:50，s1mple-zzy<notifications@github.com> 写道： 


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
