### ISSUE TITLE
你好，我想问一下，哪里有可以直接放到目录下运行的index.html呢

### ISSUE THREAD

**Issue by liwenbus** [vitozyf/lucky-draw#22]
你好，很喜欢你的这个抽奖程序，但是github太慢了，移动还墙了，需要用其他网访问，比较麻烦，想在自己的虚拟主机也弄一个，但是好像没有找到index.html这类的文件呢，请问一下我该如何转换呢？麻烦你了

**Comment by Harry-qi** [comment]
自己clone下来，打包 @liwenbus
