### ISSUE TITLE
打包部署问题

### ISSUE THREAD

**Issue by findthewayxf** [vitozyf/lucky-draw#3]
请问打包后，如何部署成静态页面。

**Comment by vitozyf** [comment]
打包后托管到任意服务器就可以拉

**Comment by findthewayxf** [comment]
主要还是相对路径的问题，最后还是手动一条条改的。
![image](https://user-images.githubusercontent.com/45526014/71542601-545cd700-29a3-11ea-8f12-f8eaad9e3e63.png)

**Comment by o0Pluto** [comment]
> 打包后托管到任意服务器就可以拉

我是个新手，请问这个能否打包成单机、无网络运行呢？用什么打包
非常喜欢这个程序，感谢作者

**Comment by findthewayxf** [comment]
> > 打包后托管到任意服务器就可以拉
> 
> 我是个新手，请问这个能否打包成单机、无网络运行呢？用什么打包
> 非常喜欢这个程序，感谢作者

本身就是静态内容，打包后，注意改下相对路径，直接可以本地运行。

**Comment by o0Pluto** [comment]
> > > 打包后托管到任意服务器就可以拉
> > 
> > 
> > 我是个新手，请问这个能否打包成单机、无网络运行呢？用什么打包
> > 非常喜欢这个程序，感谢作者
> 
> 本身就是静态内容，打包后，注意改下相对路径，直接可以本地运行。

如果我问“如何打包”会不会很过分…(⊙_⊙;)…       是不是要搭建vue环境就好了？

**Comment by vitozyf** [comment]
> > 打包后托管到任意服务器就可以拉
> 
> 我是个新手，请问这个能否打包成单机、无网络运行呢？用什么打包
> 非常喜欢这个程序，感谢作者

这个是纯前端的项目，可以无网络运行。修改下配置中的资源路径，重新打包即可

**Comment by findthewayxf** [comment]
> > > > 打包后托管到任意服务器就可以拉
> > > 
> > > 
> > > 我是个新手，请问这个能否打包成单机、无网络运行呢？用什么打包
> > > 非常喜欢这个程序，感谢作者
> > 
> > 
> > 本身就是静态内容，打包后，注意改下相对路径，直接可以本地运行。
> 
> 如果我问“如何打包”会不会很过分…(⊙_⊙;)… 是不是要搭建vue环境就好了？


[dist.zip](https://github.com/vitozyf/lucky-draw/files/4009614/dist.zip)
注意版权
