### ISSUE TITLE
如何打包为exe

### ISSUE THREAD

**Issue by zxysm** [vitozyf/lucky-draw#31]
稍微修改了一点提示信息，但是为了方便使用想打包为exe，试了一下pkg打包，好像不成功，可以说一下打包环境么？

**Comment by Fangsiyu** [comment]
同想知道

**Comment by vitozyf** [comment]
electron

**Comment by vitozyf** [comment]
electron

**Comment by tsuiwade** [comment]
https://www.cxyzjd.com/article/qq_41579104/107340431
