### ISSUE TITLE
我拿这个作为公司年会抽奖，抽完了发现有bug，呜呜呜

### ISSUE THREAD

**Issue by grace618** [vitozyf/lucky-draw#34]
不同的浏览器79人抽5个，，竟然一次就抽出相同的人，就是说这个抽奖有很大概率抽出来的是同一个 某区间段的人，我擦，
同事中了一次，特别容易中第二次，感觉就是那个区间的人概率很大

**Comment by vitozyf** [comment]
碰巧而已，代码在着放着又不是看不到。随机方法自己看吧
