### ISSUE TITLE
如何使用electron对本项目进行打包？

### ISSUE THREAD

**Issue by AntiTopQuark** [vitozyf/lucky-draw#48]
RT，请问如何使用electron对本项目进行打包

**Comment by wyfirstname** [comment]
刚好看到，就评论一番
1、使用vue add electron-builder 命令集成electron
2、使用yarn electron:build 打包即可，也可使使用npm

希望帮到你

**Comment by qiufeihong2018** [comment]
需要自动更新的话，可以加入electron-updater，加上更新流程业务

**Comment by AntiTopQuark** [comment]
我已经搞定了，十分感谢两位的帮助～
