### ISSUE TITLE
BUG:當所有人都已獲獎，但仍有獎品，會有[空值]中獎

### ISSUE THREAD

**Issue by oONIo** [vitozyf/lucky-draw#59]
當所有人都已獲獎，但仍有獎品，會有[空值]中獎
e.g.
總人數:10
獎品數:20
所有人都已中獎，剩餘獎品20-10=10
全員開關: Off
程序可以繼續抽獎，且中獎者為空值，獎品數也會減少。

**Comment by vitozyf** [comment]
在所有人都已中奖的情况下，要继续抽奖请打开全员抽奖开关，否则请不要进行抽奖动作（已经没人了，抽奖动作无意义）
